backend:
  name: github
  repo: PIKTech-Consult/stepin-hq.github.io
  branch: main
  base_url: https://stepin-landing-page-decap-proxy.misty-cloud-ad25.workers.dev
  auth_endpoint: /auth

locale: en
media_folder: public/images
public_folder: /images